var products=[
    {
        id:1,
        images:["images/1S22.jpg","images/2S22.webp","images/3S22.jpg"],
        title:"Samsung Galaxy S22",
        desc:"Samsung Galaxy S22 phone with a 6.1-inch Dynamic AMOLED 2X screen, with a Qualcomm Snapdragon 888 processor, 8GB RAM, and 128GB internal memory.",
        price:12000,
        stock:10,
    },
    {
        id:2,
        images:["images/1S21.jpg","images/2S21.webp","images/3S21.webp"],
        title:"Samsung Galaxy S21",
        desc:"Samsung Galaxy S21 phone with a 6.2-inch Dynamic AMOLED 2X screen, with a Qualcomm Snapdragon 888 processor, 8GB RAM, and 128GB internal memory.",
        price:10000,
        stock:50,
    },    
    {
        id:3,
        images:["images/A1.webp","images/A2.jpg","images/A3.jpg"],
        title:"Apple iPhone 13",
        desc:"Apple iPhone 13 phone with a 6.1-inch Super Retina XDR OLED screen, with an Apple A15 Bionic processor, 6GB RAM, and 128GB internal memory.",
        price:18000,
        stock:15,
    },    
    {
        id:4,
        images:["images/h1.jpg","images/h2.jpg","images/h3.jpg"],
        title:"Huawei P30",
        desc:"Huawei P30 phone with a 6.1-inch OLED screen, with a Huawei Kirin 980 processor, 6GB RAM, and 128GB internal memory.",
        price:8000,
        stock:100,
    },    
    {
        id:5,
        images:["images/x1.jpg","images/x2.webp","images/x3.jpg"],
        title:"Xiaomi Redmi 9",
        desc:"Xiaomi Redmi 9 phone with a 6.5-inch IPS LCD screen, with a MediaTek Helio G80 processor, 4GB RAM, and 128GB internal memory.",
        price:6500,
        stock:50,
    },    
    {
        id:6,
        images:["images/1A52.webp","images/2A52.jpg","images/3A52.jpg"],
        title:"Samsung Galaxy A52",
        desc:"Samsung Galaxy A52 phone with a 6.5-inch Super AMOLED screen, with a Qualcomm Snapdragon 720G processor, 4GB RAM.",
        price:9000,
        stock:5,
    },
]